cicodepath=$1

cd /project/AHI/SCORING/DATA/CACDIRECT/
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_AK.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_AL.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_AR.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_AZ.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_CA.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_CO.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_CT.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_DC.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_DE.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_FL.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_GA.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_HI.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_IA.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_ID.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_IL.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_IN.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_KS.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_KY.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_LA.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_MA.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_MD.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_ME.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_MI.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_MN.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_MO.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_MS.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_MT.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_NC.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_ND.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_NE.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_NH.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_NJ.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_NM.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_NV.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_NY.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_OH.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_OK.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_OR.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_PA.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_RI.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_SC.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_SD.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_TN.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_TX.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_UT.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_VA.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_VT.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_WA.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_WI.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_WV.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh rt_base_demo_with_mkey_WY.zip
/project17/CACDIRECT/CODE/$cicodepath/UPDATE_DATABASE/ftp_script.sh z2_modelscore.zip
